# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Henning Schwentner
email: hs@wps.de
description: >- # this means to ignore newlines until "baseurl:"
  Coder, Coach, Consultant @ WPS
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
url: "https://hschwentner.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
repository: "hschwentner/hschwentner.io"
twitter_username: hschwentner
github_username:  hschwentner

# Build settings
markdown: kramdown

remote_theme: pages-themes/slate@v0.2.0
#remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
- jekyll-include-cache

# Settings for theme Slate
github:
  is_project_page: false # to remove GitHub badge


# Settings for theme Minimal Mistakes

#collections:
#  domain-driven-refactorings:
#    output: true
#    permalink: /:collection/:path/

footer:
  links:
    - label: "Improve this page"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hschwentner/hschwentner.io"
    - label: "Mail"
      icon: "fas fa-envelope"
      url: "mailto:hs@wps.de"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/hschwentner"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/hschwentner"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/henningschwentner"
    - label: "Xing"
      icon: "fab fa-xing"
      url: "https://www.xing.com/profile/JHenning_Schwentner"
    - label: "Imprint"
      icon: "fas fa-balance-scale"
      url: "https://www.wps.de/impressum/"

atom_feed:
  hide: true
